
function getOfficeData() {
  return [
    {
      office: 'MEB工厂',
      buildingList: [
        { "id": "1", "building": "冲压车间" },
        { "id": "2", "building": "车身准备车间" },
        { "id": "3", "building": "车身车间" },
        { "id": "4", "building": "HVB电池车间" },
        { "id": "5", "building": "综合楼" },
        { "id": "6", "building": "MBC" },
        { "id": "7", "building": "能源中心" },
        { "id": "8", "building": "油漆注蜡车间" },
        { "id": "9", "building": "BDC" },
        { "id": "10", "building": "油漆车间" },
        { "id": "11", "building": "BA0" },
        { "id": "12", "building": "三废站" },
        { "id": "13", "building": "总装车间" },
        { "id": "14", "building": "总装准备车间LOC" },
        { "id": "16", "building": "高架立体库ASRS" },
        { "id": "17", "building": "垃圾房 " },
        { "id": "18", "building": "停车楼" },
        { "id": "19", "building": "警卫室及厂区安保设施系统" },
        { "id": "20", "building": "厂区道路及公用配套设施（含公共区域动力管线）" },
        { "id": "21", "building": "消防系统" },
        { "id": "22", "building": "厂区绿化" }
      ]
    },
    {
      office: '技术中心',
      buildingList: [
        { "id": "1", "building": "车身造型车间" },
        { "id": "2", "building": "试制车间" },
        { "id": "3", "building": "老大楼" },
        { "id": "4", "building": "研发楼" },
        { "id": "5", "building": "综合楼" },
        { "id": "6", "building": "10KV配电所" },
        { "id": "7", "building": "冷却站（浴室）" },
        { "id": "8", "building": "生活垃圾房" },
        { "id": "9", "building": "成本优化中心" },
        { "id": "10", "building": "整车试验楼" },
        { "id": "11", "building": "加油站" },
        { "id": "12", "building": "警卫室及厂区安保设施系统" },
        { "id": "13", "building": "厂区道路及公用配套设施" },
        { "id": "14", "building": "消防系统" },
        { "id": "15", "building": "厂区绿化" }
      ]
    },
    {
      office: 'IMB综合管理大楼',
      buildingList: [
        { "id": "1", "building": "IMB.1 大楼(含主辅楼)" },
        { "id": "2", "building": "IMB.1 展厅" },
        { "id": "3", "building": "IMB.2 主楼" },
        { "id": "4", "building": "IMB.2 辅楼" },
        { "id": "5", "building": "IMB停车楼" },
        { "id": "6", "building": "南警卫室(3号路)" },
        { "id": "7", "building": "北警卫室(1号路)及厂区安保设施系统" },
        { "id": "8", "building": "厂区道路及公用配套设施" },
        { "id": "9", "building": "消防系统" },
        { "id": "10", "building": "厂区绿化及水面" }
      ]
    },
    {
      office: '汽车一厂',
      buildingList: [
        { "id": "1", "building": "篮球场" },
        { "id": "2", "building": "一厂自行车棚" },
        { "id": "3", "building": "小车班" },
        { "id": "4", "building": "足球场" },
        { "id": "5", "building": "三废变电站" },
        { "id": "6", "building": "垃圾房（足球场西侧）" },
        { "id": "7", "building": "原三废处理站（足球场西侧，现保洁使用）" },
        { "id": "8", "building": "电池车间质保办公楼（原西锅炉房）" },
        { "id": "9", "building": "10KV开关站（电池车间西北侧）" },
        { "id": "10", "building": "电池车间" },
        { "id": "11", "building": "总装车间（含试车跑道及对应辅房）" },
        { "id": "12", "building": "总装充电间及加液站" },
        { "id": "13", "building": "物流周转场地" },
        { "id": "14", "building": "培训中心" },
        { "id": "15", "building": "培训中心1号实习工厂" },
        { "id": "16", "building": "电器科大楼（原培训中心教育楼）" },
        { "id": "17", "building": "来宾食堂" },
        { "id": "18", "building": "来宾食堂变电所" },
        { "id": "19", "building": "消防泵房" },
        { "id": "20", "building": "职工食堂（含工会办公楼及多功能会议室）" },
        { "id": "21", "building": "2140冷冻站房" },
        { "id": "22", "building": "E大楼（在建）" },
        { "id": "23", "building": "4号办公楼（原白宫）" },
        { "id": "24", "building": "供应部大楼（PFM临时办公楼）" },
        { "id": "25", "building": "原煤渣池" },
        { "id": "26", "building": "地磅房" },
        { "id": "27", "building": "木库（原煤场）" },
        { "id": "28", "building": "锅炉房（煤场边上）" },
        { "id": "29", "building": "铲车维修站（锅炉房与空压站之间）" },
        { "id": "30", "building": "空压站" },
        { "id": "31", "building": "蒸汽调配站" },
        { "id": "32", "building": "维修及模具制造科工装设计股" },
        { "id": "33", "building": "循环水泵房" },
        { "id": "34", "building": "1号冷泵站" },
        { "id": "35", "building": "35KV变电所 " },
        { "id": "36", "building": "ESC维修中心（原35KV降压站）" },
        { "id": "37", "building": "车身车间（含工业气站）" },
        { "id": "38", "building": "CPA1生活楼（含PFA1厂部）" },
        { "id": "39", "building": "油漆冷热泵房" },
        { "id": "40", "building": "油漆车间" },
        { "id": "41", "building": "三废站房" },
        { "id": "42", "building": "P5停车场" },
        { "id": "43", "building": "数据中心" },
        { "id": "44", "building": "质保中心" },
        { "id": "45", "building": "联合站房（质保冷冻站、10KV变电所、柴油发电机房、消防泵房）" },
        { "id": "46", "building": "雨水泵房" },
        { "id": "47", "building": "中央加油站" },
        { "id": "48", "building": "消防中心" },
        { "id": "49", "building": "北门警卫室" },
        { "id": "50", "building": "南门警卫室及厂区安保设施系统" },
        { "id": "51", "building": "厂区道路及公用配套设施" },
        { "id": "52", "building": "消防系统" },
        { "id": "53", "building": "厂区绿化" }
      ]
    },
    {
      office: '汽车二厂',
      buildingList: [
        { "id": "1", "building": "A2能源中心" },
        { "id": "2", "building": "A2三废处理站" },
        { "id": "3", "building": "A2 110kV变电所" },
        { "id": "4", "building": "A2 车体分配中心（BDC）" },
        { "id": "5", "building": "A2规划综合楼" },
        { "id": "6", "building": "A2厨房" },
        { "id": "7", "building": "A2 污水监测井" },
        { "id": "8", "building": "新车身车间" },
        { "id": "9", "building": "新车身工业气站" },
        { "id": "10", "building": "车身生活楼（原众达楼）" },
        { "id": "11", "building": "车身准备车间（新车身西侧）" },
        { "id": "12", "building": "老车身车间（一楼）" },
        { "id": "13", "building": "老车身车间（二楼）" },
        { "id": "14", "building": "老车身工业气站" },
        { "id": "15", "building": "冲压一车间" },
        { "id": "16", "building": "循环水泵房（西侧靠马路）" },
        { "id": "17", "building": "冷冻站房（医务楼西侧）" },
        { "id": "18", "building": "医务楼" },
        { "id": "19", "building": "厂区总雨水泵" },
        { "id": "20", "building": "厂区污水排放监测点" },
        { "id": "21", "building": "油库及值班室" },
        { "id": "22", "building": "新总装车间（含老总装一楼）" },
        { "id": "23", "building": "老总装二楼" },
        { "id": "24", "building": "总装准备车间" },
        { "id": "25", "building": "铲车维修中心" },
        { "id": "27", "building": "样板车间" },
        { "id": "28", "building": "档案室" },
        { "id": "30", "building": "二厂木库" },
        { "id": "31", "building": "质保尾气检测实验室（原锅炉房）" },
        { "id": "32", "building": "IT-shop floor（原35kV变电所）" },
        { "id": "33", "building": "样板生活楼（浴室）" },
        { "id": "34", "building": "灭火器仓库" },
        { "id": "35", "building": "固废管理中心（原煤棚）" },
        { "id": "36", "building": "生活垃圾房" },
        { "id": "37", "building": "地磅间(样板车间)" },
        { "id": "38", "building": "二厂南警卫室（昌吉路）及厂区安保设施系统" },
        { "id": "39", "building": "北警卫室（和静路）" },
        { "id": "40", "building": "东警卫室（阜康路）" },
        { "id": "41", "building": "西警卫室（米泉路）" },
        { "id": "42", "building": "厂区道路及公用配套设施" },
        { "id": "43", "building": "消防系统" },
        { "id": "44", "building": "厂区绿化" }
      ]
    },
    {
      office: '祥源地块',
      buildingList: [
        { "id": "1", "building": "ESC2#机加工车间及冷冻站" },
        { "id": "2", "building": "ESC办公楼" },
        { "id": "3", "building": "空压站" },
        { "id": "4", "building": "35KV降压站" },
        { "id": "5", "building": "ESC1#机加工车间（原乳化液废水处理池）" },
        { "id": "6", "building": "警卫室及厂区安保设施系统" },
        { "id": "7", "building": "厂区道路及公用配套设施" },
        { "id": "8", "building": "消防系统" },
        { "id": "9", "building": "厂区绿化" }
      ]
    },
    {
      office: '汽车三厂',
      buildingList: [
        { "id": "1", "building": "总装车间（含试车跑道）" },
        { "id": "2", "building": "老展车车间" },
        { "id": "3", "building": "2#油漆车间冷冻站房（溴化锂站房）" },
        { "id": "4", "building": "老废水处理站" },
        { "id": "5", "building": "新废水处理站" },
        { "id": "6", "building": "西门天然气调压站" },
        { "id": "7", "building": "老油漆车间" },
        { "id": "8", "building": "新油漆车间" },
        { "id": "9", "building": "质控中心" },
        { "id": "10", "building": "三厂食堂" },
        { "id": "11", "building": "老循环水泵房" },
        { "id": "12", "building": "新循环水泵房" },
        { "id": "13", "building": "老车身车间" },
        { "id": "14", "building": "新车身车间" },
        { "id": "15", "building": "车身工业气站" },
        { "id": "16", "building": "老冲压车间" },
        { "id": "17", "building": "底板车间" },
        { "id": "18", "building": "35KV变电站" },
        { "id": "19", "building": "新冲压车间" },
        { "id": "20", "building": "试模中心及模具车间" },
        { "id": "21", "building": "成品车停车场（含办公室）" },
        { "id": "22", "building": "P2停车楼" },
        { "id": "23", "building": "消防值班室" },
        { "id": "24", "building": "新浴室生活楼" },
        { "id": "25", "building": "木库（原发二锅炉房）" },
        { "id": "26", "building": "工业垃圾房" },
        { "id": "27", "building": "分布式能源天然气调压站" },
        { "id": "28", "building": "自行车棚" },
        { "id": "29", "building": "新锅炉房" },
        { "id": "30", "building": "分布式能源中心" },
        { "id": "31", "building": "售后服务拆装车间（原锅炉房）" },
        { "id": "32", "building": "新展车车间（原干煤棚）" },
        { "id": "33", "building": "老浴室生活楼" },
        { "id": "34", "building": "加液站" },
        { "id": "35", "building": "油库" },
        { "id": "36", "building": "冷冻机房" },
        { "id": "37", "building": "铲车维修中心" },
        { "id": "38", "building": "垃圾房" },
        { "id": "39", "building": "1#空压站" },
        { "id": "40", "building": "2#空压站及循环水泵房" },
        { "id": "41", "building": "塔山路警卫室（西）" },
        { "id": "42", "building": "于田路警卫室（东）" },
        { "id": "43", "building": "曹安路警卫室（南）及厂区安保设施系统" },
        { "id": "44", "building": "厂区道路及公用配套设施" },
        { "id": "45", "building": "消防系统" },
        { "id": "46", "building": "厂区绿化" }
      ]
    },
    {
      office: '发一',
      buildingList: [
        { "id": "1", "building": "地磅房" },
        { "id": "2", "building": "员工活动中心" },
        { "id": "3", "building": "消防泵房" },
        { "id": "4", "building": "售后分析室" },
        { "id": "5", "building": "质保中心" },
        { "id": "6", "building": "5号办公楼" },
        { "id": "7", "building": "质量控制中心" },
        { "id": "8", "building": "专业维修中心（徐小平工作室）" },
        { "id": "9", "building": "发一木库" },
        { "id": "10", "building": "外购件仓库" },
        { "id": "11", "building": "冷冻机房" },
        { "id": "12", "building": "加油站" },
        { "id": "13", "building": "危险品仓库" },
        { "id": "14", "building": "危险品仓库（原油化库）" },
        { "id": "15", "building": "垃圾堆场" },
        { "id": "16", "building": "工料废仓库（原干煤棚）" },
        { "id": "17", "building": "煤渣池西侧两栋建筑" },
        { "id": "18", "building": "原煤渣池" },
        { "id": "19", "building": "原锅炉房（一楼为祥源维修中心，二楼为财务档案室）" },
        { "id": "20", "building": "溴化锂站房" },
        { "id": "21", "building": "水泵站" },
        { "id": "22", "building": "空压站" },
        { "id": "23", "building": "三废处理站" },
        { "id": "24", "building": "东昌仓库/办公用品仓库" },
        { "id": "25", "building": "托盘料架车场地" },
        { "id": "26", "building": "发一食堂" },
        { "id": "27", "building": "发一食堂办公室" },
        { "id": "28", "building": "感应头维修中心" },
        { "id": "29", "building": "HS办公楼（原托儿所）" },
        { "id": "30", "building": "消防中心" },
        { "id": "31", "building": "铲车维修中心" },
        { "id": "32", "building": "职工生活楼（浴室）" },
        { "id": "33", "building": "降压站" },
        { "id": "34", "building": "保洁办公室" },
        { "id": "35", "building": "工业气站" },
        { "id": "36", "building": "二号厂房（含办公楼）" },
        { "id": "37", "building": "加压泵房" },
        { "id": "38", "building": "物流卸货棚（原一号路）" },
        { "id": "39", "building": "三号厂房（含办公楼）" },
        { "id": "40", "building": "1号门警卫室" },
        { "id": "41", "building": "2号门警卫室" },
        { "id": "42", "building": "3号门警卫室及厂区安保设施系统" },
        { "id": "43", "building": "4号门警卫室" },
        { "id": "44", "building": "厂区道路及公用配套设施" },
        { "id": "45", "building": "消防系统" },
        { "id": "46", "building": "厂区绿化" }
      ]
    },
    {
      office: '发二',
      buildingList: [
        { "id": "1", "building": "联合厂房" },
        { "id": "2", "building": "联合厂房（二）" },
        { "id": "3", "building": "测功房" },
        { "id": "4", "building": "综合仓库" },
        { "id": "5", "building": "氨气站" },
        { "id": "6", "building": "丙烷站" },
        { "id": "7", "building": "变速器油库" },
        { "id": "8", "building": "地磅" },
        { "id": "9", "building": "食堂" },
        { "id": "10", "building": "轿车维修中心" },
        { "id": "11", "building": "P3停车场（含办公楼）" },
        { "id": "12", "building": "警卫室及厂区安保设施系统" },
        { "id": "13", "building": "厂区道路及公用配套设施" },
        { "id": "14", "building": "消防系统" },
        { "id": "15", "building": "厂区绿化" }
      ]
    }, 
    {
      office: '发三',
      buildingList: [
        { "id": "1", "building": "能源中心" },
        { "id": "2", "building": "35kV降压站" },
        { "id": "3", "building": "废水处理站" },
        { "id": "4", "building": "发动机车间（含下沉式卸货棚）" },
        { "id": "5", "building": "地磅房" },
        { "id": "6", "building": "油库" },
        { "id": "7", "building": "工业气站（车间西北角）" },
        { "id": "8", "building": "工业气站（车间东侧偏南）" },
        { "id": "9", "building": "新建垃圾房" },
        { "id": "10", "building": "警卫室及厂区安保设施系统" },
        { "id": "11", "building": "厂区道路及公用配套设施" },
        { "id": "12", "building": "消防系统" },
        { "id": "13", "building": "厂区绿化" }
      ]
    },
    {
      office: 'TAMPA',
      buildingList: [
        { "id": "1", "building": "生产辅房" },
        { "id": "2", "building": "消防泵房" },
        { "id": "3", "building": "1#分析车间" },
        { "id": "4", "building": "2#分析车间" },
        { "id": "5", "building": "警卫室及厂区安保设施系统" },
        { "id": "6", "building": "厂区道路及公用配套设施" },
        { "id": "7", "building": "消防系统" },
        { "id": "8", "building": "厂区绿化" }
      ]
    },
    {
      office: '试车场及107亩',
      buildingList: [
        { "id": "1", "building": "试车场调度室（小白楼）" },
        { "id": "2", "building": "试车场综合楼（含食堂）" },
        { "id": "3", "building": "35KV降压站" },
        { "id": "4", "building": "ADP试验楼" },
        { "id": "5", "building": "排放试验楼" },
        { "id": "6", "building": "NVH声学中心" },
        { "id": "7", "building": "碰撞中心" },
        { "id": "8", "building": "电磁兼容中心" },
        { "id": "9", "building": "消防站" },
        { "id": "10", "building": "发动机研发试验中心" },
        { "id": "11", "building": "发动机楼配套动力站房" },
        { "id": "12", "building": "零部件试验楼 (翼锐楼)" },
        { "id": "13", "building": "车辆准备车间" },
        { "id": "14", "building": "试验零件周转车间" },
        { "id": "15", "building": "新能源整车车间" },
        { "id": "16", "building": "零部件和底盘综合试验楼（在建）" },
        { "id": "17", "building": "南警卫室及厂区安保设施系统" },
        { "id": "18", "building": "厂区道路及公用配套设施" },
        { "id": "19", "building": "消防系统" },
        { "id": "20", "building": "厂区绿化" }
      ]
    }
  ]
}

module.exports = {
  getOfficeData: getOfficeData
};